# Generated by Django 4.2 on 2023-04-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="firstname",
            field=models.CharField(default=False, max_length=20),
        ),
    ]
