# Generated by Django 4.2 on 2023-05-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0002_user_firstname"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecturer",
            name="classes",
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.AddField(
            model_name="lecturer",
            name="course",
            field=models.CharField(default=False, max_length=20),
        ),
    ]
