# Generated by Django 4.2 on 2023-05-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0003_lecturer_classes_lecturer_course"),
    ]

    operations = [
        migrations.CreateModel(
            name="subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_value", models.CharField(default=False, max_length=50)),
                ("checkbox_value", models.CharField(default=False, max_length=50)),
            ],
        ),
    ]
