# Generated by Django 4.2 on 2023-05-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0005_remove_subject_checkbox_value"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="input_value",
        ),
        migrations.AddField(
            model_name="subject",
            name="data",
            field=models.JSONField(default=False),
        ),
    ]
