# Generated by Django 4.2 on 2023-05-15 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0006_remove_subject_input_value_subject_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="studentmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject1", models.FloatField(default=False, max_length=20)),
                ("subject2", models.FloatField(default=False, max_length=20)),
                ("subject3", models.FloatField(default=False, max_length=20)),
                ("subject4", models.FloatField(default=False, max_length=20)),
                ("subject5", models.FloatField(default=False, max_length=20)),
                ("subject6", models.FloatField(default=False, max_length=20)),
                ("languages", models.FloatField(default=False, max_length=20)),
                (
                    "s1",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="app1.student"
                    ),
                ),
            ],
        ),
    ]
