# Generated by Django 4.2 on 2023-05-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0007_studentmark"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="data",
            field=models.JSONField(default=dict),
        ),
    ]
