# Generated by Django 4.2 on 2023-05-17 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0009_alter_studentmark_s1"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecturer",
            name="image",
            field=models.ImageField(default=False, upload_to="pictures"),
        ),
        migrations.AlterField(
            model_name="studentmark",
            name="s1",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="app1.student"
            ),
        ),
    ]
