# Generated by Django 4.2 on 2023-06-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0011_staff_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="image",
            field=models.ImageField(default=False, upload_to="studentpicture"),
        ),
    ]
