# Generated by Django 4.2 on 2023-06-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_student_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_clerk',
            field=models.BooleanField(default=False),
        ),
    ]
