# Generated by Django 4.2 on 2023-06-05 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0013_user_is_clerk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentmark",
            name="s1",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
