# Generated by Django 4.2 on 2023-06-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0015_alter_studentmark_s1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentmark",
            name="languages",
            field=models.FloatField(
                blank=True, default=False, max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="studentmark",
            name="subject1",
            field=models.FloatField(
                blank=True, default=False, max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="studentmark",
            name="subject2",
            field=models.FloatField(
                blank=True, default=False, max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="studentmark",
            name="subject3",
            field=models.FloatField(
                blank=True, default=False, max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="studentmark",
            name="subject4",
            field=models.FloatField(
                blank=True, default=False, max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="studentmark",
            name="subject5",
            field=models.FloatField(
                blank=True, default=False, max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="studentmark",
            name="subject6",
            field=models.FloatField(
                blank=True, default=False, max_length=20, null=True
            ),
        ),
    ]
