# Generated by Django 4.2 on 2023-06-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0016_alter_studentmark_languages_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentmark",
            name="languages",
            field=models.FloatField(default=False, max_length=20),
        ),
        migrations.AlterField(
            model_name="studentmark",
            name="subject1",
            field=models.FloatField(default=False, max_length=20),
        ),
        migrations.AlterField(
            model_name="studentmark",
            name="subject2",
            field=models.FloatField(default=False, max_length=20),
        ),
        migrations.AlterField(
            model_name="studentmark",
            name="subject3",
            field=models.FloatField(default=False, max_length=20),
        ),
        migrations.AlterField(
            model_name="studentmark",
            name="subject4",
            field=models.FloatField(default=False, max_length=20),
        ),
        migrations.AlterField(
            model_name="studentmark",
            name="subject5",
            field=models.FloatField(default=False, max_length=20),
        ),
        migrations.AlterField(
            model_name="studentmark",
            name="subject6",
            field=models.FloatField(default=False, max_length=20),
        ),
    ]
