# Generated by Django 4.2 on 2023-06-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0018_subject_k"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentmark",
            name="languages",
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.AlterField(
            model_name="studentmark",
            name="subject1",
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.AlterField(
            model_name="studentmark",
            name="subject2",
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.AlterField(
            model_name="studentmark",
            name="subject3",
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.AlterField(
            model_name="studentmark",
            name="subject4",
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.AlterField(
            model_name="studentmark",
            name="subject5",
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.AlterField(
            model_name="studentmark",
            name="subject6",
            field=models.CharField(default=False, max_length=20),
        ),
    ]
