# Generated by Django 4.2 on 2023-06-07 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0019_alter_studentmark_languages_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="k",
        ),
    ]
