# Generated by Django 4.2 on 2023-06-09 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0020_remove_subject_k"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="studentmark",
            new_name="studentmark1",
        ),
        migrations.CreateModel(
            name="studentmark2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject1", models.CharField(default=False, max_length=20)),
                ("subject2", models.CharField(default=False, max_length=20)),
                ("subject3", models.CharField(default=False, max_length=20)),
                ("subject4", models.CharField(default=False, max_length=20)),
                ("subject5", models.CharField(default=False, max_length=20)),
                ("subject6", models.CharField(default=False, max_length=20)),
                ("languages", models.CharField(default=False, max_length=20)),
                (
                    "s1",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="app1.student"
                    ),
                ),
            ],
        ),
    ]
