# Generated by Django 4.2 on 2023-06-20 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_rename_studentmark_studentmark1_studentmark2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='firstname',
        ),
    ]
