# Generated by Django 4.2 on 2023-06-27 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0022_remove_user_firstname"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="place",
        ),
    ]
