# Generated by Django 4.2 on 2023-06-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0023_remove_student_place"),
    ]

    operations = [
        migrations.CreateModel(
            name="appliedinfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                ("contact_no", models.CharField(max_length=100)),
                ("email_id", models.EmailField(max_length=100)),
                ("gender", models.CharField(max_length=100)),
                ("adharno", models.CharField(max_length=100)),
                ("dob", models.CharField(max_length=100)),
                ("place_of_birth", models.CharField(max_length=100)),
                ("caste", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=100)),
                ("parents_name", models.CharField(max_length=100)),
                ("occupation", models.CharField(max_length=100)),
                ("parent_no", models.CharField(max_length=100)),
                ("income", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("course", models.CharField(max_length=100)),
                ("language", models.CharField(max_length=100)),
                ("regno", models.CharField(max_length=100)),
                ("pay", models.CharField(default="", max_length=100)),
            ],
        ),
    ]
