# Generated by Django 4.2 on 2023-06-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0025_user_is_librarian"),
    ]

    operations = [
        migrations.CreateModel(
            name="bookdetails",
            fields=[
                (
                    "bookid",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("bookimg", models.ImageField(default=False, upload_to="books")),
                ("bookname", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=100)),
                ("copies", models.IntegerField()),
                ("total_copies", models.IntegerField()),
                ("publication", models.CharField(max_length=100)),
                ("type", models.CharField(default="Others", max_length=100)),
                ("status", models.CharField(default="Available", max_length=100)),
                ("borrower", models.CharField(max_length=100)),
            ],
        ),
    ]
