# Generated by Django 4.2 on 2023-06-29 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sessions", "0001_initial"),
        ("app1", "0026_bookdetails"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="session",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sessions.session",
            ),
        ),
    ]
